### ISSUE TITLE
"4 services" section

### ISSUE THREAD

**Issue by terbouchi** [terbouchi/C2N2#6]

**Comment by Fitahsoufian** [comment]
done

**Comment by terbouchi** [comment]
![Untitled](https://user-images.githubusercontent.com/42858300/107383652-7ce55900-6af1-11eb-967f-26f856e6bbcb.png)

**Comment by terbouchi** [comment]
i think its not done yet, can u review this problem ? thanks !

**Comment by terbouchi** [comment]
good now
